language: node_js
node_js:
  - "iojs"
sudo: false
install:
  - npm install
  - npm run build
addons:
  sauce_connect:
    username: 'karissa'
    secure: "lSfGNSatKmhaMWxucxgxEFZ9FtGJuQQ34/0nk6fiUCL3RLHTeltoSIieybTxMYd04Opv1eupLxlypZ4dOtTtHRRa5lMP3OJCcUbVw7O33bDlaqVn9V13sWl3UxE+fPBDa++ef9qWmcdgNG+RbYfulowoN67lLSm/MZJ+cU/oEqybNVNKAYD8TzxdK+WSBJwv/Ayheg5/uT7lJvW0suS09kZHBR4z8FZj+cs9txFXss5LcfkJ9QA/Kfuk3njdEcv3UXCkLXOpTr2Cu4++r93OHJ16/207gHcBbSERO74i0IAd6twaYO1t9LU/+xiKCDJziYKMSuLfDvtX73Vu6sq7I7xeLw6VYwAyBcWt5hGtqvbmR5AoNmXjxGHS0J91YJPuNUwVXgiYfp/xMmfHK2LUkeA6LB0rFS9VPV/H46R0ZbZKEPMY+bfrcZXdpkdaATGur/8JW43rfuKjdJer1LDENvk0CXYUNI0SqlPkU0kpFTfNG+nCmWCdjJK1NhawctKL4zIgIc8lX08p80ukKxbFE1HMPujLnMqSLEKykFR8vbQzBsE1W2/sTZrSYzJgKbnnhODfEu/g28ZYuKKDtVw23BI771kxg+O67MM6oQFzNzRkTVl23wp2jptW2HHx/22wfCeUFbWUgdDfNQP/i9aikhzot6OLexFUrQk8+KiXNh0="
